strategy:
  maxParallel: 2
  matrix:
    lts:
      node_version: 12.x
    latest:
      node_version: 13.x

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    displayName: Use Node
    inputs:
      versionSpec: $(node_version)

  - script: npm install
    displayName: Install Dependencies

  - script: npm test
    displayName: Run Tests
