type Level0_Short = "AAAAAAAAAAAAAAAA" | "BBBBBBBBBBBBBBBB" | "CCCCCCCCCCCCCCCC";
type Level0_Long =
	| "AAAAAAAAAAAAAAAA"
	| "BBBBBBBBBBBBBBBB"
	| "CCCCCCCCCCCCCCCC"
	| "DDDDDDDDDDDDDDDD"
	| "EEEEEEEEEEEEEEEE"
	| "FFFFFFFFFFFFFFFF"
	| "GGGGGGGGGGGGGGGG"
	| "HHHHHHHHHHHHHHHH";
type Level1_Short = {
	myprop: "AAAAAAAAAAAAAAAA" | "BBBBBBBBBBBBBBBB" | "CCCCCCCCCCCCCCCC";
};
type Level1_Long = {
	myprop:
		| "AAAAAAAAAAAAAAAA"
		| "BBBBBBBBBBBBBBBB"
		| "CCCCCCCCCCCCCCCC"
		| "DDDDDDDDDDDDDDDD"
		| "EEEEEEEEEEEEEEEE"
		| "FFFFFFFFFFFFFFFF"
		| "GGGGGGGGGGGGGGGG"
		| "HHHHHHHHHHHHHHHH";
};
