type Union_Level0_Long =
	| "AAAAAAAAAAAAAAAA"
	| "BBBBBBBBBBBBBBBB"
	| "CCCCCCCCCCCCCCCC"
	| "DDDDDDDDDDDDDDDD"
	| "EEEEEEEEEEEEEEEE"
	| "FFFFFFFFFFFFFFFF"
	| "GGGGGGGGGGGGGGGG"
	| "HHHHHHHHHHHHHHHH";
