name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Version (e.g. "1.0.0-rc1")'

jobs:
  publish:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Install node
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install --prefer-offline --no-fund --no-progress

    - name: Initialize deployment
      id: deployment
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const tag = /^[0-9]+\.[0-9]+\.[0-9]+$/.test("${{ github.event.inputs.version }}") ? 'latest' : 'preview';
          const deployment = await github.rest.repos.createDeployment({
            environment: tag,
            ref: '${{ github.sha }}',
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          core.setOutput('id', deployment.data.id);
          core.setOutput('tag', tag);

    - name: Parameters
      run: |
        echo SHA ${{ github.sha }}
        echo Branch ${{ github.ref }}
        echo Version ${{ github.event.inputs.version }}
        echo NPM Tag ${{ steps.deployment.outputs.tag }}
        echo Deployment ${{ steps.deployment.outputs.id }}

    - name: Build & Test
      run: |
        npm run build:eslint -- --version ${{ github.event.inputs.version }}
        npm run build:prettier -- --version ${{ github.event.inputs.version }}
        npm run test

    - name: Create Release
      id: release
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const release = await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: 'v${{ github.event.inputs.version }}',
            target_commitish: context.sha,
            name: '${{ github.event.inputs.version }}',
            body: '',
            draft: false,
            prerelease: '${{ steps.deployment.outputs.tag }}' !== 'latest'
          });
          core.setOutput('upload_url', release.data.upload_url);

    - name: Pack "legacy"
      working-directory: packages/legacy
      run: npm pack

    - name: Pack "commonjs"
      working-directory: packages/commonjs
      run: npm pack

    - name: Pack "esmodules"
      working-directory: packages/esmodules
      run: npm pack

    - name: Pack "typescript"
      working-directory: packages/typescript
      run: npm pack

    - name: Pack "prettier"
      working-directory: packages/prettier
      run: npm pack

    - name: Attach "legacy"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./packages/legacy/wildpeaks-eslint-config-legacy-${{ github.event.inputs.version }}.tgz
        asset_name: legacy.tgz
        asset_content_type: application/gzip

    - name: Attach "commonjs"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./packages/commonjs/wildpeaks-eslint-config-commonjs-${{ github.event.inputs.version }}.tgz
        asset_name: commonjs.tgz
        asset_content_type: application/gzip

    - name: Attach "esmodules"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./packages/esmodules/wildpeaks-eslint-config-esmodules-${{ github.event.inputs.version }}.tgz
        asset_name: esmodules.tgz
        asset_content_type: application/gzip

    - name: Attach "typescript"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./packages/typescript/wildpeaks-eslint-config-typescript-${{ github.event.inputs.version }}.tgz
        asset_name: typescript.tgz
        asset_content_type: application/gzip

    - name: Attach "prettier"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./packages/prettier/wildpeaks-prettier-config-${{ github.event.inputs.version }}.tgz
        asset_name: prettier.tgz
        asset_content_type: application/gzip

    - name: Set token
      run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_DEPLOY_KEY }}

    - name: Publish "legacy"
      run: npm publish --tag ${{ steps.deployment.outputs.tag }}
      working-directory: packages/legacy

    - name: Publish "commonjs"
      run: npm publish --tag ${{ steps.deployment.outputs.tag }}
      working-directory: packages/commonjs

    - name: Publish "esmodules"
      run: npm publish --tag ${{ steps.deployment.outputs.tag }}
      working-directory: packages/esmodules

    - name: Publish "typescript"
      run: npm publish --tag ${{ steps.deployment.outputs.tag }}
      working-directory: packages/typescript

    - name: Publish "prettier"
      run: npm publish --tag ${{ steps.deployment.outputs.tag }}
      working-directory: packages/prettier

    - name: On success
      if: success()
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: '${{ steps.deployment.outputs.id }}',
            state: 'success'
          });

    - name: On error
      if: failure() || cancelled()
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: '${{ steps.deployment.outputs.id }}',
            state: 'failure'
          });
